"""Sidebar configuration + trigger/display for the optional AI scientific
interpretation feature (see ai_agent.py). Off by default; nothing here ever
calls an LLM unless the user both picks a provider AND clicks the button.
"""
import os
from dataclasses import dataclass

import streamlit as st

from ai_agent import (
    DEFAULT_MODELS,
    PROVIDERS,
    AIAgentError,
    build_user_prompt,
    generate_interpretation,
)
from atlas_regions import get_atlas_source
from models import RegionEntry

_ENV_KEY_NAMES = {
    "Claude (Anthropic)": "ANTHROPIC_API_KEY",
    "ChatGPT (OpenAI)": "OPENAI_API_KEY",
}


@dataclass(frozen=True)
class AIConfig:
    enabled: bool
    provider: str = ""
    api_key: str = ""
    model: str = ""


def render_ai_sidebar_config() -> AIConfig:
    with st.sidebar:
        st.divider()
        st.header("🤖 AI Interpretation (optional)")
        st.caption(
            "Bring your own API key — this app never makes LLM calls on your behalf "
            "unless you configure a provider here and click Generate below."
        )
        provider = st.selectbox("Provider", ["Disabled", *PROVIDERS])
        if provider == "Disabled":
            return AIConfig(enabled=False)

        env_default = os.environ.get(_ENV_KEY_NAMES[provider], "")
        api_key = st.text_input(
            f"{provider} API key",
            value=env_default,
            type="password",
            help="Kept in this browser session only — never written to disk. "
                 f"You can also set {_ENV_KEY_NAMES[provider]} as an environment "
                 "variable to prefill this field.",
        )
        model = st.text_input(
            "Model",
            value=DEFAULT_MODELS[provider],
            help="A small/cheap model is used by default to keep costs low. "
                 "Check your provider's current model catalog if this name goes stale.",
        )
        return AIConfig(enabled=bool(api_key), provider=provider, api_key=api_key, model=model)


def _cache_key(regions: list[RegionEntry], config: AIConfig) -> tuple:
    return (tuple((r.name, r.kcal) for r in regions), config.provider, config.model)


def render_ai_interpretation(regions: list[RegionEntry], config: AIConfig):
    if not config.enabled:
        return

    st.divider()
    st.subheader("🤖 AI Interpretation")
    st.caption(
        "Generated by a general-purpose LLM from its background neuroscience knowledge — "
        "**not** a literature search, and it will not cite specific papers. Verify any claim "
        "against primary sources before relying on it."
    )

    key = _cache_key(regions, config)
    cache = st.session_state.setdefault("ai_result_cache", {})

    if st.button("Generate AI interpretation", key="ai_generate_btn"):
        atlas_sources = {r.name: get_atlas_source(r.name) for r in regions}
        prompt = build_user_prompt(regions, atlas_sources)
        with st.spinner(f"Asking {config.provider}…"):
            try:
                text = generate_interpretation(config.provider, config.api_key, config.model, prompt)
                cache[key] = text
            except AIAgentError as e:
                st.error(str(e))
                return

    if key in cache:
        st.markdown(cache[key])
    else:
        st.info("Click **Generate AI interpretation** above to run this (uses your API key).")
